version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gestion-produit:
    build: .
    container_name: gestion-produit
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/gestion-produit
    depends_on:
      - mongo

volumes:
  mongo_data: